name: Watch Announcements

permissions:
  contents: write

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch:

jobs:
  task:
    environment: Announcements
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: archive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Job
        run: docker run -e BEGIN_ID=${{ vars.BEGIN_ID }} -e END_ID=${{ vars.END_ID }} -e QPS=${{ vars.QPS }} -e GIT_EMAIL=${{ github.actor }}@users.noreply.github.com -e GIT_USER=${{ github.actor }} -v ./:/app --rm ghcr.io/${{ github.repository }}/job:latest robomaster-diff-job

      - name: Push Archive
        run: |
          git push
          
        
      
